spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sbkcoding@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
